from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = [
  "git tag -f v{{version.major}} v{{version}}",
  "git tag -f v{{version.major}}.{{version.minor}} v{{version}}",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"
skip_ci = "[skip ci]"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
