on:
  push:
    branches: ["*"]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check conventional commits
        uses: nagyben/cocogitto-action@main

  tag-version:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - check-conventional-commits
    outputs:
      current-version: ${{ steps.bump-version.outputs.current-version }}
      version-was-bumped: ${{ steps.bump-version.outputs.version-was-bumped }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump-version
        uses: ./.github/bump-version

  create-release:
    if: ${{needs.tag-version.outputs.version-was-bumped == 'true' && github.ref == 'refs/heads/main'}}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - tag-version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true # For the changelog
          ref: refs/tags/v${{ needs.tag-version.outputs.current-version }}

      - uses: nagyben/cocogitto-action@main

      - name: Generate changelog
        run: cog changelog --at v${{ needs.tag-version.outputs.current-version }} -t full_hash > GITHUB_CHANGELOG.md

      - run: |
          set -euo pipefail
          echo "Creating release from tag $tag"
          gh release create "$tag" \
          --notes-file GITHUB_CHANGELOG.md \
          --repo "$GITHUB_REPOSITORY"
        if: ${{ needs.tag-version.outputs.version-was-bumped }}
        env:
          tag: "v${{ needs.tag-version.outputs.current-version }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
