on:
  push:
    branches: ["*"]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check conventional commits
        uses: cocogitto/cocogitto-action@v3.6

  tag-version:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    outputs:
      version-was-bumped: ${{ steps.bump-version.outputs.version-was-bumped }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump-version
        uses: ./.github/bump-version

  create-release:
    if: ${{needs.tag-version.outputs.version-was-bumped == 'true' && github.ref == 'refs/heads/main'}}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - tag-version
    steps:
      - name: Generate changelog
        run: cog changelog --at v${{ steps.release.outputs.current-version }} -t full_hash > GITHUB_CHANGELOG.md

      - run: |
          set -euo pipefail
          echo "Creating release from tag $tag"
          gh release create "$tag" \
          --notes-file GITHUB_CHANGELOG.md \
          --repo "$GITHUB_REPOSITORY"
        if: ${{ steps.release.outputs.version-was-bumped }}
        env:
          tag: "v${{ steps.release.outputs.current-version }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
